name: package sb3

on:
    push:
        branches:
            - main

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: check for changes
              id: check_changes
              uses: actions/github-script@v7
              with:
                script: |
                  const changedFiles = await github.paginate(
                    github.rest.repos.getCommit,
                    {
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      ref: context.sha,
                      },
                      (response) => response.data.files.map((file) => file.filename)
                      );
                      return {
                        changedFiles.includes("Assets/project.json")
                        };

            - name: setup python
              if: steps.check_changes.outputs.return == 'true'
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'

            - name: install dependencies
              if: steps.check_changes.outputs.return == 'true'
              run: python -m pip install --upgrade pip

            - name: run sb3-repackage.py
              if: steps.check_changes.outputs.return == 'true'
              run: python sb3-repackage.py
            
            - name: upload artifact
              if: steps.check_changes.outputs.return == 'true'
              uses: actions/upload-artifact@v4
              with:
                name: sb3-output
                path: ./CarDrivingSimulator2.sb3
                

